name: Generate Snake Game from Contributions

on:
  push:
    branches:
      - main  # A branch que você está usando
  schedule:
    - cron: '0 0 * * *'  # Executa automaticamente todos os dias (opcional)

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # Passo 2: Gerar o Snake Game
      - name: Generate Snake Game
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            github-snake.svg
            github-snake-dark.svg?palette=github-dark
            github-snake.svg?color_snake=orange&color_dots=#c4b4ff,#a684ff,#7f22fe,#5d0ec0,#2f0d68

      - name: Verificar arquivos gerados
        run: ls -lah

      # Passo 3: Criar a pasta dist e mover o arquivo para lá
      - name: Move generated file to dist/
        run: |
          mkdir -p dist  
          mv *.svg dist/ || echo "Nenhum arquivo encontrado para mover"
      # Passo 4: Commit e Push do arquivo
      - name: Commit and push the generated Snake Game to the repository
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          git add dist/github-snake.svg
          git commit -m "Add generated snake game GIF"
          git push
